const fs = require('fs');

const rawText = `
1. WOLVES - PINK DRAGON ENERGY
2. CHUG - PARTY PUNCH (LEMONADE, FRUIT PUNCH, WATERMELON LEMONADE)
3. PERSEUS - PERSEUS
4. level - CURB THE CURVE INFUSED WITH LEMON & GINGER
5. LIL POP - CREAM SODA, LEMON SQZ, GINGER, LYCHEE
6. BROTHER BEANS COFFEE - COLD BREW COFFEE BLACK
7. VODN - Pineapple Peach Premium Vodka Seltzer
8. CHUG - PARTY PUNCH (FRUIT PUNCH, LEMONADE, WATERMELON LEMONADE)
9. BOW - RAINBOW BEER
10. HQD - KING OF TASTE
11. DAWN - COCO AZURE ENERGY DRINK
12. FOREPLAY - HARD SELTZER PINEAPPLE
13. WOLVES ENERGY - PINK DRAGON
14. MOROUNA - Heavy Activity Drink MINT
15. Witch's Water - KEY LIME High Seltzer
16. DAWN - COCO AZURE ENERGY DRINK
17. kavanua - NOBLE KAVA + GINGER SPARKLING DRINK
18. DISCY - VODKA MIXED DRINK CAFFEINE FREE
19. vita Melon - watermelon peach Pressed sparkling WATERMELON JUICE
20. NEVER - HOLY GRAIL ESPRESSO SYRUP
21. VODN - Pineapple Peach
22. GRAM CO - High Seltzer (KEY LIME, SUMMER BERRY, GUAVA)
23. kavanua - NOBLE KAVA SPARKLING DRINK
24. Witch's Water - KEY LIME High Seltzer
25. PURE FREEDOM - BERRY SPARKLING WATER
26. NEVER - OREGON ESPRESSO SYRUP
27. kavanua - SPARKLING DRINK NOBLE KAVA + GINGER
28. BLACKOUT - MANGO, LEMON LIME, STRAWBERRY KIWI, DARK CHERRY, LEMON MANGO
29. NEVER - HOLY GRAIL ESPRESSO
30. BOW - RAINBOW BEER ORIGINAL LIGHT LAGER
31. HQD - KING OF TASTE ICED PEACH ENERGY DRINK
32. BOW - RAINBOW BEER
33. vita Melon - Watermelon
34. PERSEUS - PERSEUS
35. MOROUNAH - CANNAMS.INFUSED SPARKLING WATER
36. COCO RESERVE - COCO RESERVE
37. VELOCITY - LEMON-LIME PATENTED GLUTATHIONE FORMULA
38. Witch's Water - KEY LIME High Seltzer
39. FLYHT ENERGY - STRAWBERRY
40. WOLVES ENERGY - PINK DRAGON
41. FOREPLAY - HARD SELTZER PINEAPPLE
42. MOROUNAH - Moderate Activity Drink MINT
43. JOKYTE - VODKA WITH NATURAL FLAVOR
44. BLACKOUT - MANGO, LEMON LIME, STRAWBERRY KIWI
45. NEVER - MIDNIGHT OIL ESPRESSO SYRUP
46. NEVER - HOLY GRAIL ESPRESSO SYRUP
47. SOUTH DOWNS - SOLSTICE Proper Sussex Cider
48. MOROUNAH - Light Activity Drink MINT
49. PERSEUS - PERSEUS
50. CHUG - PARTY PUNCH (LEMONADE, FRUIT PUNCH, WATERMELON LEMONADE)
51. HUNTER & GREY - STRAWBERRY DAIQUIRI
52. NEVER - RICH KID ESPRESSO SYRUP
53. MOROUNA - Activity Drink MINT (Light, Moderate, Heavy)
54. VODN - Pineapple Peach
55. GRAM CO - High Seltzer SUMMER BERRY
56. HQD - KING OF TASTE ICED PEACH ENERGY DRINK
57. GRAM CO - High Seltzer SUMMER BERRY
58. MOROUNAH - Go beyond Hydration
59. BOW - RAINBOW BEER ORIGINAL LIGHT LAGER
60. DAWN - COCO AZURE ENERGY DRINK
61. RADIANT ENERGY - LEMON BLAST, GALACTIC RUSH, CHERRY BOMB, NITRO MANGO, SUPERNOVA SPLASH, TROPICAL BLAST
62. COCO RESERVE - COCO RESERVE
63. COLADA RUSH - ZERO SUGAR
64. HUNTER & GREY - STRAWBERRY DAIQUIRI
65. LIL POP - CREAM SODA, LEMON SQZ, GINGER, LYCHEE
66. kavanua - NOBLE KAVA + GINGER SPARKLING DRINK
67. JOKYTE - VODKA WITH NATURAL FLAVOR AND ARTIFICIAL COLORS
68. level - CURB THE CURVE INFUSED WITH LEMON & GINGER
69. COLADA RUSH - ZERO SUGAR
70. BOW - JUICE
71. DISCY - VODKA MIXED DRINK CAFFEINE FREE
72. PURE FREEDOM - BERRY SPARKLING WATER
73. CHUG - PARTY PUNCH (LEMONADE, FRUIT PUNCH, WATERMELON LEMONADE)
74. NEVER - HOLY GRAIL ESPRESSO SYRUP
75. BROTHER BEANS COFFEE - COLD BREW COFFEE BLACK
76. kavanua - NOBLE KAVA + GINGER SPARKLING DRINK
77. HUNTER & GREY - STRAWBERRY DAIQUIRI
78. MOROUNAH - CANNAMS.INFUSED SPARKLING WATER
79. VODN - Pineapple Peach Premium Vodka Seltzer
80. GRAM CO - High Seltzer (KEY LIME, SUMMER BERRY, GUAVA)
81. NEVER - OREGON ESPRESSO SYRUP
82. MOROUNAH - GO BEYOND HYDRATION
83. vita Melon - Watermelon Pressed sparkling
84. SOUTH DOWNS - EXBERRY MENT Proper Sussex Cider
85. WOLVES ENERGY - PINK DRAGON
86. BROTHER BEANS COFFEE - COLD BREW COFFEE BLACK
87. FOREPLAY - HARD SELTZER PINEAPPLE
88. NEVER - OREGON ESPRESSO SYRUP
89. MOROUNAH - GO BEYOND HYDRATION
90. SOUTH DOWNS - EXBERRY MENT Proper Sussex Cider
91. kavanua - NOBLE KAVA + GINGER SPARKLING DRINK
92. FLYHT ENERGY - MANGO
93. VELOCITY - LEMON-LIME PATENTED GLUTATHIONE FORMULA
94. Strjøna - Mango HARD SELTZER
95. FOREPLAY - HARD SELTZER PINEAPPLE
96. FLYHT ENERGY - MANGO
97. PERSEUS - PERSEUS
98. PURE FREEDOM - BERRY SPARKLING WATER
99. CHUG - PARTY PUNCH (LEMONADE, FRUIT PUNCH, WATERMELON LEMONADE)
100. vita Melon - Watermelon Pressed sparkling WATERMELON JUICE
`;

const lines = rawText.trim().split('\n');
const items = lines.map(line => {
  const match = line.match(/^\d+\.\s+(.*?)\s*-\s*(.*)$/);
  if (match) {
    return { brand: match[1].trim(), product: match[2].trim() };
  }
  return { brand: "Unknown", product: "Unknown" };
});

let tsCode = fs.readFileSync('src/data/canLabelProjects.ts', 'utf8');

let count = 0;
// We'll match each object block by looking for "brand": "..." and "product": "..."
// and replacing them sequentially
tsCode = tsCode.replace(/"brand":\s*"[^"]*",\s*"product":\s*"[^"]*"/g, (match) => {
  if (count < items.length) {
    const replacement = '"brand": "' + items[count].brand.replace(/"/g, '\\\\"') + '",\n    "product": "' + items[count].product.replace(/"/g, '\\\\"') + '"';
    count++;
    return replacement;
  }
  return match;
});

fs.writeFileSync('src/data/canLabelProjects.ts', tsCode);
console.log('Successfully updated 100 labels!');
